function findDay(date){return availability?.days?.find(d=>d.date===date)||null}
function statusLabel(day){if(!day)return '取得結果なし';return day.status?.label||'判定保留'}
function isSelectable(day){return !!day&&['available','full'].includes(day.status?.code)}
function slotSummary(day,includeFull=false){if(!day)return '';const slots=includeFull?(day.slots||[]):(day.availableSlots||[]);if(!slots.length)return '';return slots.map(s=>`${s.start}〜${s.end}（${s.durationMinutes}分枠）`).join('、')}
function dayStateClass(day){const code=day?.status?.code;return code==='noSlots'?'no-slots':code==='full'?'full':code==='available'?'available':'error'}
function renderReservations(resetSelection=false){const target=$('menuDate').value;const dates=[0,1,2,3].map(i=>addDays(target,i));if(resetSelection){selectedReserveDates.clear();const first=findDay(target);if(isSelectable(first))selectedReserveDates.add(target)}const list=$('reserveList');list.innerHTML='';dates.forEach((date,index)=>{const day=findDay(date);const selectable=isSelectable(day);if(!selectable)selectedReserveDates.delete(date);const row=document.createElement('label');row.className='reserve-day'+(selectable?'':' disabled');const checked=selectedReserveDates.has(date);const stateClass=dayStateClass(day);let detail='';if(day?.status?.code==='available')detail=slotSummary(day);else if(day?.status?.code==='full')detail='すべての予約枠が満席です';else if(day?.status?.code==='noSlots')detail='この日は予約枠がありません';else if(day?.status?.code==='notOpen')detail='受付開始前です';else detail='この日付の取得結果がありません';row.innerHTML=`<input type="checkbox" data-reserve-date="${date}" ${checked?'checked':''} ${selectable?'':'disabled'}><div class="reserve-day-main"><div class="reserve-day-top"><span class="reserve-date">${formatDate(date,true)}${index===0?' 対象日':''}</span><span class="reserve-state ${stateClass}">${esc(statusLabel(day))}</span></div><div class="reserve-slots">${esc(detail)}</div></div>`;list.appendChild(row)});list.querySelectorAll('[data-reserve-date]').forEach(input=>input.addEventListener('change',()=>{if(input.checked)selectedReserveDates.add(input.dataset.reserveDate);else selectedReserveDates.delete(input.dataset.reserveDate);updateTodayOption();generatePost()}));updateTodayOption();updateReserveHeader();generatePost()}
function updateTodayOption(){const today=localIso();const show=selectedReserveDates.has(today)&&findDay(today)?.status?.code==='available';$('todayTimeOption').hidden=!show}
function updateReserveHeader(){const badge=$('reserveBadge');const selected=[...selectedReserveDates];if(availabilityLoading){$('reserveTitle').textContent='予約状況を取得中です';badge.textContent='取得中';badge.className='status-pill loading';return}if(!availability?.ok){$('reserveTitle').textContent='予約状況を取得できませんでした';badge.textContent='取得失敗';badge.className='status-pill error';return}const count=selected.length;$('reserveTitle').textContent=count?`${count}日分を投稿文に使用します`:'掲載する日を選択してください';badge.textContent='実データ';badge.className='status-pill';if(availability.fetchedAt){const d=new Date(availability.fetchedAt);$('fetchTime').textContent=`取得：${d.toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`}}
async function loadAvailability(resetSelection=false){availabilityLoading=true;updateReserveHeader();$('reserveMessage').textContent='Airリザーブの取得結果を読み込んでいます。';$('reserveMessage').className='note';try{const res=await fetch(`data/availability.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(!data?.ok||!Array.isArray(data.days))throw new Error('取得データが不正です');availability=data;$('reserveMessage').textContent='予約状況を読み込みました。';$('reserveMessage').className='note';const age=Date.now()-new Date(data.fetchedAt).getTime();if(Number.isFinite(age)&&age>2*60*60*1000){$('reserveMessage').textContent='取得から2時間以上経過しています。投稿前に最新データへ更新されているか確認してください。';$('reserveMessage').className='note warning-note'}}catch(e){availability=null;selectedReserveDates.clear();$('reserveMessage').textContent='予約状況を読み込めませんでした。通信状態を確認して再度お試しください。';$('reserveMessage').className='note error-note'}finally{availabilityLoading=false;renderReservations(resetSelection)}}
function buildReservationLines(){const today=localIso();const showTodayTime=document.querySelector('input[name="todayTime"]:checked')?.value!=='hide';const lines=[];[...selectedReserveDates].sort().forEach(date=>{const day=findDay(date);if(!day)return;const name=date===today?'本日':formatDate(date,true);if(day.status?.code==='available'){const available=day.availableSlots||[];const minRemaining=Math.min(...available.map(s=>Number.isFinite(s.remaining)?s.remaining:99));if(date===today&&showTodayTime){const slots=slotSummary(day);lines.push(`${name}は、${slots}に空きがございます。`)}else if(minRemaining<=1){lines.push(`${name}は空き枠が残り僅かです。`)}else{lines.push(`${name}はご予約いただけるお時間がございます。`)}}else if(day.status?.code==='full'){lines.push(`${name}は満席となっております。`)}});return lines}
function setActionsDisabled(disabled){$('copy').disabled=disabled;$('openX').disabled=disabled}
function generatePost(){const date=formatDate($('menuDate').value);const menu=buildMenuLine(selectedMenus());const opening=pick(learnedPatterns.openings,1);const weather=applyEmoji(pick(learnedPatterns.weather[$('weather').value]),'weather');const limited=$('limitedInfo').value.trim();const reservationLines=buildReservationLines().map(x=>applyEmoji(x,'reserve'));const closing=applyEmoji(pick(learnedPatterns.closings,2),'close');const p=[date];if(opening)p.push('',opening);p.push('',menu);if(weather)p.push('',weather);if(reservationLines.length)p.push('',...reservationLines);if(limited)p.push('',limited);p.push('','最新状況は予約ページよりご確認ください。',closing);const text=p.join('\n');$('preview').textContent=text;$('charCount').textContent=text.length+'文字';$('generatedAt').textContent='更新 '+new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});setActionsDisabled(!text.trim())}
function realtime(){clearTimeout(inputTimer);inputTimer=setTimeout(generatePost,220)}
