function findDay(date){return availability?.days?.find(d=>d.date===date)||null}
function isBusinessDay(day){return !!day&&['available','full','notOpen'].includes(day.status?.code)}
function isClosedDay(day){return day?.status?.code==='noSlots'}
function isSelectable(day){return !!day&&['available','full'].includes(day.status?.code)}
function sortedAvailabilityDays(){return [...(availability?.days||[])].sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function findNextBusinessDay(afterDate){return sortedAvailabilityDays().find(day=>day.date>afterDate&&isBusinessDay(day))||null}
function dayDistance(from,to){const [fy,fm,fd]=from.split('-').map(Number);const [ty,tm,td]=to.split('-').map(Number);return Math.round((Date.UTC(ty,tm-1,td)-Date.UTC(fy,fm-1,fd))/86400000)}
function getPostContext(){const postDate=$('postDate')?.value||localIso();const selectedMenuDate=$('menuDate')?.value||postDate;const postDay=findDay(postDate);const selectedMenuDay=findDay(selectedMenuDate);const postClosed=isClosedDay(postDay);const menuClosed=isClosedDay(selectedMenuDay);let closedDate=null;if(menuClosed)closedDate=selectedMenuDate;else if(postClosed)closedDate=postDate;let nextBusiness=null;if(menuClosed)nextBusiness=findNextBusinessDay(selectedMenuDate);else if(postClosed)nextBusiness=findNextBusinessDay(postDate);const effectiveMenuDate=menuClosed?(nextBusiness?.date||selectedMenuDate):selectedMenuDate;return {postDate,selectedMenuDate,effectiveMenuDate,postDay,selectedMenuDay,postClosed,menuClosed,closedDate,nextBusiness,holidayMode:postClosed||menuClosed}}
function relativeMenuDateText(postDate,date){const distance=dayDistance(postDate,date);if(distance===1)return `明日${formatDate(date,true)}`;if(distance===2)return `明後日${formatDate(date,true)}`;return `次回営業日${formatDate(date,true)}`}
function renderMenuDateStatus(){const box=$('menuDateStatus');if(!box)return;const ctx=getPostContext();if(availabilityLoading){box.className='menu-date-status loading';box.innerHTML='<strong>営業日を確認中です</strong><span>Airリザーブの予約枠を読み込んでいます。</span>';return}if(!availability?.ok){box.className='menu-date-status error';box.innerHTML='<strong>営業日を判定できません</strong><span>予約状況を取得できないため、日付を確認して投稿してください。</span>';return}if(ctx.menuClosed){const next=ctx.nextBusiness;box.className='menu-date-status closed';box.innerHTML=`<div class="menu-date-status-top"><strong>${formatDate(ctx.selectedMenuDate,true)}は定休日です</strong><span class="menu-date-badge closed">定休日</span></div><span>${next?`${relativeMenuDateText(ctx.postDate,next.date)}のメニュー投稿として自動で作成します。`:'取得範囲内に次回営業日が見つかりません。'}</span>${next?`<span class="next-business">次回営業日：${formatDate(next.date,true)}（${esc(next.status?.label||'営業日')}）</span>`:''}`;return}if(ctx.postClosed){const next=ctx.nextBusiness;box.className='menu-date-status closed';box.innerHTML=`<div class="menu-date-status-top"><strong>${ctx.postDate===localIso()?'本日':formatDate(ctx.postDate,true)}は定休日です</strong><span class="menu-date-badge closed">定休日投稿</span></div><span>${next?`${relativeMenuDateText(ctx.postDate,ctx.effectiveMenuDate)}のメニューを案内します。`:'メニュー対象日の内容で定休日投稿を作成します。'}</span>`;return}if(isBusinessDay(ctx.selectedMenuDay)){box.className='menu-date-status open';box.innerHTML=`<div class="menu-date-status-top"><strong>${formatDate(ctx.selectedMenuDate,true)}の営業メニュー</strong><span class="menu-date-badge open">営業日</span></div><span>通常の営業日投稿として作成します。</span>`;return}box.className='menu-date-status neutral';box.innerHTML='<strong>営業日判定なし</strong><span>この日付は取得範囲外です。予約ページで営業日をご確認ください。</span>'}
function uniqueAvailableSlots(day){const map=new Map();for(const slot of day?.availableSlots||[]){const key=`${slot.start}|${slot.end}|${slot.durationMinutes}`;if(!map.has(key))map.set(key,slot)}return [...map.values()]}
function totalRemaining(day){const available=uniqueAvailableSlots(day);const values=available.map(s=>Number(s.remaining)).filter(n=>Number.isFinite(n)&&n>0);return values.length?values.reduce((sum,n)=>sum+n,0):available.length}
function reserveBand(day){if(!day)return {code:'error',label:'取得結果なし'};if(day.status?.code==='full')return {code:'full',label:'満席'};if(day.status?.code==='noSlots')return {code:'no-slots',label:'定休日'};if(day.status?.code==='notOpen')return {code:'not-open',label:'受付開始前'};if(day.status?.code!=='available')return {code:'error',label:day.status?.label||'判定保留'};const remaining=totalRemaining(day);if(remaining<=3)return {code:'few',label:'残り枠わずか'};if(remaining<=8)return {code:'some',label:'まだ空きあり'};return {code:'plenty',label:'比較的余裕あり'}}
function slotSummary(day){const slots=uniqueAvailableSlots(day);if(!slots.length)return '';return slots.map(s=>`${s.start}〜${s.end}（${s.durationMinutes}分枠）`).join('、')}
function reservationBaseDate(){return getPostContext().effectiveMenuDate}
function renderReservations(resetSelection=false){const ctx=getPostContext();const base=reservationBaseDate();const postDate=ctx.postDate;const dates=[0,1,2,3].map(i=>addDays(base,i));if(resetSelection){selectedReserveDates.clear();const first=findDay(base);if(isSelectable(first))selectedReserveDates.add(base)}const list=$('reserveList');list.innerHTML='';dates.forEach((date,index)=>{const day=findDay(date);const selectable=isSelectable(day);if(!selectable)selectedReserveDates.delete(date);const row=document.createElement('label');row.className='reserve-day'+(selectable?'':' disabled')+(day?.status?.code==='noSlots'?' closed-day':'');const checked=selectedReserveDates.has(date);const band=reserveBand(day);let detail='';if(day?.status?.code==='available'){const remaining=totalRemaining(day);detail=`残り合計 ${remaining}枠`;const times=slotSummary(day);if(times)detail+=`／${times}`}else if(day?.status?.code==='full')detail='すべての予約枠が満席です';else if(day?.status?.code==='noSlots')detail='予約枠がないため定休日として扱います';else if(day?.status?.code==='notOpen')detail='予約受付開始前です';else detail='この日付の取得結果がありません';const dateNotes=[];if(index===0)dateNotes.push(ctx.holidayMode?'次回営業日':'対象日');if(date===postDate)dateNotes.push('投稿日');row.innerHTML=`<input type="checkbox" data-reserve-date="${date}" ${checked?'checked':''} ${selectable?'':'disabled'}><div class="reserve-day-main"><div class="reserve-day-top"><span class="reserve-date">${formatDate(date,true)}${dateNotes.length?` ${dateNotes.join('・')}`:''}</span><span class="reserve-state ${band.code}">${esc(band.label)}</span></div><div class="reserve-slots">${esc(detail)}</div></div>`;list.appendChild(row)});list.querySelectorAll('[data-reserve-date]').forEach(input=>input.addEventListener('change',()=>{if(input.checked)selectedReserveDates.add(input.dataset.reserveDate);else selectedReserveDates.delete(input.dataset.reserveDate);updateTodayOption();generatePost()}));renderMenuDateStatus();updateTodayOption();updateReserveHeader();updateWeatherDisplay();generatePost()}
function updateTodayOption(){const postDate=$('postDate').value;const show=selectedReserveDates.has(postDate)&&findDay(postDate)?.status?.code==='available';$('todayTimeOption').hidden=!show}
function updateReserveHeader(){const badge=$('reserveBadge');const selected=[...selectedReserveDates];if(availabilityLoading){$('reserveTitle').textContent='予約状況を取得中です';badge.textContent='取得中';badge.className='status-pill loading';return}if(!availability?.ok){$('reserveTitle').textContent='予約状況を取得できませんでした';badge.textContent='取得失敗';badge.className='status-pill error';return}const ctx=getPostContext();const count=selected.length;$('reserveTitle').textContent=ctx.holidayMode?(count?`定休日投稿に${count}日分の予約状況を使用します`:'次回営業日の予約状況を選択してください'):(count?`${count}日分を投稿文に使用します`:'掲載する日を選択してください');badge.textContent=ctx.holidayMode?'定休日投稿':'実データ';badge.className=ctx.holidayMode?'status-pill holiday':'status-pill';if(availability.fetchedAt){const d=new Date(availability.fetchedAt);$('fetchTime').textContent=`取得：${d.toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}`}}
async function loadAvailability(resetSelection=false){availabilityLoading=true;updateReserveHeader();renderMenuDateStatus();$('reserveMessage').textContent='Airリザーブの取得結果を読み込んでいます。';$('reserveMessage').className='note';try{const res=await fetch(`data/availability.json?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(!data?.ok||!Array.isArray(data.days))throw new Error('取得データが不正です');availability=data;$('reserveMessage').textContent='予約状況を読み込みました。予約枠がない日は定休日として判定します。';$('reserveMessage').className='note';const age=Date.now()-new Date(data.fetchedAt).getTime();if(Number.isFinite(age)&&age>2*60*60*1000){$('reserveMessage').textContent='取得から2時間以上経過しています。投稿前に最新データへ更新されているか確認してください。';$('reserveMessage').className='note warning-note'}}catch(e){availability=null;selectedReserveDates.clear();$('reserveMessage').textContent='予約状況を読み込めませんでした。通信状態を確認して再度お試しください。';$('reserveMessage').className='note error-note'}finally{availabilityLoading=false;renderReservations(resetSelection)}}
function reservationComment(day,name){const remaining=totalRemaining(day);if(remaining<=3)return `${name}は残り枠がわずかとなっております。`;if(remaining<=8)return `${name}はまだ空きがございます。`;return `${name}は比較的ゆったりご案内できます。`}
function buildReservationLines(){const postDate=$('postDate').value;const showPostDateTime=document.querySelector('input[name="todayTime"]:checked')?.value!=='hide';const lines=[];[...selectedReserveDates].sort().forEach(date=>{const day=findDay(date);if(!day)return;const name=date===postDate?'本日':formatDate(date,true);if(day.status?.code==='available'){let text=reservationComment(day,name);if(date===postDate&&showPostDateTime){const slots=slotSummary(day);if(slots)text+=`\n空き時間：${slots}`;}lines.push(text)}else if(day.status?.code==='full'){lines.push(`${name}は満席となっております。`)}});return lines}
function buildHolidayIntroduction(ctx){if(!ctx.holidayMode)return [];const closedDate=ctx.closedDate;const nextDate=ctx.menuClosed?ctx.nextBusiness?.date:ctx.effectiveMenuDate;const closedText=closedDate===ctx.postDate?'本日は定休日です。':`${formatDate(closedDate,true)}は定休日です。`;if(!nextDate||nextDate===closedDate)return [closedText,'次回営業日は改めてご案内いたします。'];return [closedText,`${relativeMenuDateText(ctx.postDate,nextDate)}のメニューです。`]}
function setActionsDisabled(disabled){$('copy').disabled=disabled;$('openX').disabled=disabled}
function generatePost(){const ctx=getPostContext();const displayDate=ctx.holidayMode?formatDate(ctx.postDate):formatDate(ctx.effectiveMenuDate);const menu=buildMenuLine(selectedMenus());const opening=ctx.holidayMode?'':pick(learnedPatterns.openings,1);const weather=applyEmoji(buildWeatherText(),'weather');const limited=$('limitedInfo').value.trim();const reservationLines=buildReservationLines().map(x=>applyEmoji(x,'reserve'));const closing=applyEmoji(pick(learnedPatterns.closings,2),'close');const p=[displayDate];const holidayIntro=buildHolidayIntroduction(ctx);if(holidayIntro.length)p.push('',...holidayIntro);else if(opening)p.push('',opening);p.push('',menu);if(weather)p.push('',weather);if(reservationLines.length)p.push('',...reservationLines);if(limited)p.push('',limited);p.push('','最新状況は予約ページよりご確認ください。',closing);const text=p.join('\n');$('preview').textContent=text;$('charCount').textContent=text.length+'文字';$('generatedAt').textContent='更新 '+new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});setActionsDisabled(!text.trim())}
function realtime(){clearTimeout(inputTimer);inputTimer=setTimeout(generatePost,220)}
